[build]
  publish = "."
  command = "echo 'No build required - static site'"

[[redirects]]
  from = "/safety-wear"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/safety"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/vest*"
  to = "/index.html#categories"
  status = 200

[[redirects]]
  from = "/pricing"
  to = "/index.html#pricing"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/index.html#contact"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"